Locailable/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
#from django.contrib.auth import views as auth_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('business/', include('business.urls')),
    path('', include('users.urls')),
    #path('users/', include('users.urls', namespace='users')),  # Include the users app URLs
    
#    path('api/', include('api.urls')),
#
#    path('reset_password/', auth_views.PasswordResetView.as_view(template_name="reset_password.html"),
#         name="reset_password"),
#
#    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(template_name="reset_password_sent.html"),
#         name="password_reset_done"),
#
#    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="reset.html"),
#         name="password_reset_confirm"),
#
#    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(template_name="reset_password_complete.html"),
#         name="password_reset_complete"),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

djangoProject1/urls.py
from django.contrib import admin

from djangoProject1.views import index

from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index),
    path('users/', include('users.urls')),
    path('businesses/', include('business.urls')),
    path('reviews/', include('reviews.urls'))]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('', views.home, name='home'),
    path('home/', views.home, name='home'),
    path('signup/', views.user_signup, name='user_signup'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('profile/', views.user_profile, name='user_profile'),
    #path('profile/<uuid:owner_id>/', views.userProfile, name='user_profile'),
    path('profile/update/', views.update_profile, name='update_profile'),
    path('profile/delete/', views.delete_profile, name='delete_profile'),
    #path('add_review/', views.add_review, name='add_review'),
    #path('vote_review/<int:review_id>/<str:value>/', views.vote_review, name='vote_review'),
]

users/models.py
from django.contrib.auth.models import AbstractUser, Group, Permission
from django.db import models
import uuid

class User(models.Model):
    user_id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    username = models.CharField(max_length=255, unique=True)
    email = models.EmailField(unique=True)
    password = models.CharField(max_length=255)
    phone = models.CharField(max_length=20)
    created_at = models.DateTimeField(auto_now_add=True)

    USERNAME_FIELD = 'username'

    user_groups = models.ManyToManyField(Group, related_name='users', blank=True, help_text='The groups this user belongs to.')
    user_permissions = models.ManyToManyField(Permission, related_name='users', blank=True, help_text='Specific permissions for this user.')

    def __str__(self):
        return str(self.username)

    class Meta:
        ordering = ['created_at']

    @property
    def imageURL(self):
        try:
            url = self.profile_image.url
        except ValueError:
            url = ''
        return url

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import User

class UserSignupForm(forms.ModelForm):
    password1 = forms.CharField(
        label='Password',
        widget=forms.PasswordInput(attrs={'class': 'input'}),
    )
    password2 = forms.CharField(
        label='Password confirmation',
        widget=forms.PasswordInput(attrs={'class': 'input'}),
    )

    class Meta:
        model = User
        fields = ['name', 'email', 'username']
        labels = {
            'name': 'Name',
        }
        widgets = {
            'name': forms.TextInput(attrs={'class': 'input'}),
            'email': forms.EmailInput(attrs={'class': 'input'}),
            'username': forms.TextInput(attrs={'class': 'input'}),
        }

    def clean_password2(self):
        # Check that the two password entries match
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2

    def save(self, commit=True):
        # Save the provided password in hashed format
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user

class UserProfileForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['name', 'email', 'username']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'input'}),
            'email': forms.EmailInput(attrs={'class': 'input'}),
            'username': forms.TextInput(attrs={'class': 'input'}),
        }

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, logout, authenticate, get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .forms import UserSignupForm, UserProfileForm

User = get_user_model()

def home(request):
    return render(request, 'users/home.html')


def user_signup(request):
    if request.method == 'POST':
        form = UserSignupForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            messages.success(request, 'User account was created!')
            return redirect('users:home')
        else:
            # Print form errors to console for debugging
            print(form.errors)
    else:
        form = UserSignupForm()

    return render(request, 'users/user_signup.html', {'form': form})

def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            messages.success(request, 'Login successful!')
            return redirect('users:home')  # Redirect to home on successful login
        else:
            messages.error(request, 'Invalid username or password.')

    return render(request, 'users/user_login.html')
def user_logout(request):
    logout(request)
    messages.info(request, 'User was logged out!')
    return redirect('users:home')

@login_required
def user_profile(request):
    return render(request, 'users/user_profile.html')

@login_required
def update_profile(request):
    return render(request, 'users/update_profile.html')

@login_required
def delete_profile(request):
    return render(request, 'users/delete_profile.html')

users/templates/users/add_review.html
<!-- users/templates/users/add_review.html -->

{% extends 'base.html' %}

{% block content %}
  <h2>Add Review</h2>
  <form method="post" action="{% url 'add_review' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Add Review</button>
  </form>
{% endblock %}

users/templates/users/delete_profile.html
<!-- users/templates/users/delete_profile.html -->

{% extends 'base.html' %}

{% block content %}
  <h2>Delete Profile</h2>
  <p>Are you sure you want to delete your account?</p>
  <form method="post" action="{% url 'delete_profile' %}">
    {% csrf_token %}
    <button type="submit">Delete Account</button>
  </form>
{% endblock %}

users/templates/users/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Locailable</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <style>
        body {
            font-family: "Times New Roman", Georgia, Serif;
        }

        h1, h2, h3, h4, h5, h6 {
            font-family: "Playfair Display";
            letter-spacing: 5px;
        }

        .search-container {
            text-align: center;
            padding: 10px;
        }

        .search-container input[type=text] {
            padding: 10px;
            width: 300px;
        }

        .search-container button {
            padding: 10px;
        }

        /* Stil eklenen bölüm başlangıcı */
        #about h1 {
            font-size: 24px; /* Yazı boyutunu küçültmek için */
            text-align: center; /* Ortalamak için */
        }
        /* Stil eklenen bölüm sonu */
    </style>
    {% load static %}

</head>

<body>

    <!-- Navbar (sit on top) -->
    <div class="w3-top">
        <div class="w3-bar w3-white w3-padding w3-card" style="letter-spacing:4px;">
            <a href="#home" class="w3-bar-item w3-button">LOCAILABLE</a>
            <!-- Right-sided navbar links. Hide them on small screens -->
            <div class="w3-right w3-hide-small">
            <a href="javascript:void(0);" onclick="scrollToTopRatedPlaces()" class="w3-bar-item w3-button">Places</a>
                <a href="{% url 'users:login' %}" class="w3-bar-item w3-button">Sign up / Log in</a>
                <!-- Remove the "Contact" link -->
            </div>
            <!-- Search Engine -->
            <div class="search-container w3-hide-small">
                <form action="{% url 'search_business' %}" method="GET">
                    <input type="text" placeholder="Search..." name="q">
                    <button type="submit">Search</button>
                </form>
            </div>
        </div>
    </div>

    <!-- Header -->
    <header class="w3-display-container w3-content w3-wide" style="max-width:1600px;min-width:500px" id="home">
        <img class="w3-image" src="/w3images/hamburger.jpg" alt="Hamburger Catering" width="1600" height="800">
        <div class="w3-display-bottomleft w3-padding-large w3-opacity">
            <h1 class="w3-xxlarge">Le Catering</h1>
        </div>
    </header>

    <!-- Page content -->
    <div class="w3-content" style="max-width:1100px">

        <!-- About Section -->
        <div id="top-rated-places">
<div class="w3-row w3-padding-64" id="places">
    <div class="w3-col m6 w3-padding-large w3-hide-small"></div>

    <div class="w3-row w3-padding-64" id="top-rated-places">
        <!-- Centered "Top Rated Places" heading -->
        <h1 style="font-weight: bold; text-align: center;">Top Rated Places</h1><br>
    </div>
</div>
<!-- First Photo Grid -->
<div class="w3-row-padding">
    <div class="w3-third w3-container w3-margin-bottom">
        <img src="{% static 'business/cafecadde.jpg' %}" alt="Cafe Cadde" style="width:100%; height:200px;">
        <div class="w3-container w3-white">
            <p><b>Cafe Cadde</b></p>
            <p>Address: {{ business.location }}</p>
            <p>Rating: {{ business.rating }}</p>
            <p>Capacity: {{ business.rating }}</p>
            <p>Available Tables: {{ business.rating }}</p>
        </div>
    </div>
    <div class="w3-third w3-container w3-margin-bottom">
        <img src="{% static 'business/crepe.jpeg' %}" alt="The Crepe Escape" style="width:100%; height:200px;">
        <div class="w3-container w3-white">
            <p><b>The Crepe Escape</b></p>
            <p>Address: {{ business.location }}</p>
            <p>Rating: {{ business.rating }}</p>
            <p>Capacity: {{ business.rating }}</p>
            <p>Available Tables: {{ business.rating }}</p>        </div>
    </div>
    <div class="w3-third w3-container">
        <img src="{% static 'business/strada.jpeg' %}" alt="The Crepe Escape" style="width:100%; height:200px;">
        <div class="w3-container w3-white">
            <p><b>Strada</b></p>
            <p>Address: {{ business.location }}</p>
            <p>Rating: {{ business.rating }}</p>
            <p>Capacity: {{ business.rating }}</p>
            <p>Available Tables: {{ business.rating }}</p>
        </div>
    </div>
</div>
        <!-- Second Photo Grid -->
        <div class="w3-row-padding">
    <div class="w3-third w3-container w3-margin-bottom">
        <img src="{% static 'business/draft.jpeg' %}" alt="Cafe Cadde" style="width:100%; height:200px;">
        <div class="w3-container w3-white">
            <p><b>Draft</b></p>
            <p>Address: {{ business.location }}</p>
            <p>Rating: {{ business.rating }}</p>
            <p>Capacity: {{ business.rating }}</p>
            <p>Available Tables: {{ business.rating }}</p>
        </div>
    </div>
    <div class="w3-third w3-container w3-margin-bottom">
        <img src="{% static 'business/artois.jpeg' %}" alt="The Crepe Escape" style="width:100%; height:200px;">
        <div class="w3-container w3-white">
            <p><b>Artois Cadde - Cocktail Bar & Chef Restaurant</b></p>
            <p>Address: {{ business.location }}</p>
            <p>Rating: {{ business.rating }}</p>
            <p>Capacity: {{ business.rating }}</p>
            <p>Available Tables: {{ business.rating }}</p>        </div>
    </div>
    <div class="w3-third w3-container">
        <img src="{% static 'business/noir.jpeg' %}" alt="The Crepe Escape" style="width:100%; height:200px;">
        <div class="w3-container w3-white">
            <p><b>Brasserie Noir</b></p>
            <p>Address: {{ business.location }}</p>
            <p>Rating: {{ business.rating }}</p>
            <p>Capacity: {{ business.rating }}</p>
            <p>Available Tables: {{ business.rating }}</p>
        </div>
    </div>
</div>
        <!-- Pagination -->
        <div class="w3-center w3-padding-32">
            <div class="w3-bar">
                <a href="#" class="w3-bar-item w3-button w3-hover-black">«</a>
                <a href="#" class="w3-bar-item w3-black w3-button">1</a>
                <a href="#" class="w3-bar-item w3-button w3-hover-black">2</a>
                <a href="#" class="w3-bar-item w3-button w3-hover-black">3</a>
                <a href="#" class="w3-bar-item w3-button w3-hover-black">4</a>
                <a href="#" class="w3-bar-item w3-button w3-hover-black">»</a>
            </div>
        </div>

    </div>

    <!-- Footer -->
    <footer class="w3-row-padding w3-padding-32">
        <div class="w3-third">
            <h3>About Locailable</h3>
            <p>Who We Are</p>
            <p>Contact Us</p>
        </div>
        <div class="w3-third w3-serif">
            <h3>POPULAR TAGS</h3>
            <p>
                <span class="w3-tag w3-dark-grey w3-small w3-margin-bottom">Istanbul</span> <span
                    class="w3-tag w3-dark-grey w3-small w3-margin-bottom">Dinner</span> <span
                    class="w3-tag w3-dark-grey w3-small w3-margin-bottom">Salmon</span> <span
                    class="w3-tag w3-dark-grey w3-small w3-margin-bottom">Drinks</span> <span
                    class="w3-tag w3-dark-grey w3-small w3-margin-bottom">Chicken</span> <span
                    class="w3-tag w3-dark-grey w3-small w3-margin-bottom">Fried</span> <span
                    class="w3-tag w3-dark-grey w3-small w3-margin-bottom">Fish</span> <span
                    class="w3-tag w3-dark-grey w3-small w3-margin-bottom">Duck</span>
            </p>
        </div>
    </footer>
<script>
    function scrollToTopRatedPlaces() {
        var topRatedPlacesSection = document.getElementById("top-rated-places");

        if (topRatedPlacesSection) {
            // Scroll smoothly to the top-rated-places section
            topRatedPlacesSection.scrollIntoView({ behavior: 'smooth' });
        }
    }
</script>
</body>

</html>

users/templates/users/register.html
<!-- users/templates/users/register.html -->
{% extends 'base.html' %}

{% block title %}Register{% endblock %}

{% block content %}
  <div style="text-align: center; margin-top: 50px;">
    <h1>{{ page|title }}</h1>

    <!-- Registration Form -->
    <form method="POST" action="{% url 'users:register' %}" id="registerForm" style="text-align: left; padding: 20px; border: 1px solid #ccc; border-radius: 8px;">
      {% csrf_token %}

      <label for="{{ form.username.id_for_label }}">Username:</label>
      <br>
      <input type="text" name="{{ form.username.name }}" id="{{ form.username.id_for_label }}" required>
      <br><br>

      <label for="{{ form.first_name.id_for_label }}">First Name:</label>
      <br>
      <input type="text" name="{{ form.first_name.name }}" id="{{ form.first_name.id_for_label }}" required>
      <br><br>

      <label for="{{ form.last_name.id_for_label }}">Last Name:</label>
      <br>
      <input type="text" name="{{ form.last_name.name }}" id="{{ form.last_name.id_for_label }}" required>
      <br><br>

      <label for="{{ form.email.id_for_label }}">Email:</label>
      <br>
      <input type="email" name="{{ form.email.name }}" id="{{ form.email.id_for_label }}" required>
      <br><br>

      <label for="{{ form.password1.id_for_label }}">Password:</label>
      <br>
      <input type="password" name="{{ form.password1.name }}" id="{{ form.password1.id_for_label }}" pattern="(?=.*\d)(?=.*[a-z])(?=.*[A-Z]).{8,}" title="Must contain at least one number, one lowercase letter, one uppercase letter, and at least 8 characters" required>
      <br><br>

      <label for="{{ form.password2.id_for_label }}">Confirm Password:</label>
      <br>
      <input type="password" name="{{ form.password2.name }}" id="{{ form.password2.id_for_label }}" required>
      <br><br>

      <p style="font-weight: bold;">Password must contain at least one number, one lowercase letter, one uppercase letter, and at least 8 characters.</p>

      <button type="submit" style="padding: 10px; margin-top: 10px; display: block; font-weight: bold;">Register</button>
    </form>
  </div>
{% endblock %}

users/templates/users/update_profile.html
<!-- users/templates/users/update_profile.html -->

{% extends 'base.html' %}

{% block content %}
  <h2>Update Profile</h2>
  <form method="post" action="{% url 'update_profile' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Update</button>
  </form>
{% endblock %}

users/templates/users/user_login.html
<!-- users/templates/users/user_login.html -->
{% extends 'base.html' %}

{% block title %}Your Login Page Title{% endblock %}

{% block content %}
  <div style="display: flex; flex-direction: column; align-items: center; justify-content: center; height: 100vh;">
    <a href="{% url 'users:home' %}" style="text-decoration: none; color: black; font-size: 24px;">Locailable</a>
    <h1>{{ page|title }}</h1>

    <!-- Login Form -->
    <form method="POST" action="{% url 'users:login' %}" id="loginForm" style="max-width: 300px; text-align: left; padding: 20px; border: 1px solid #ccc; border-radius: 8px; display: flex; flex-direction: column; align-items: center;">
      {% csrf_token %}
      <!-- Add your form fields here -->
      <label for="id_username">Username:</label>
      <input type="text" name="username" id="id_username" class="input-field" required>
      <br>
      <label for="id_password">Password:</label>
      <input type="password" name="password" id="id_password" class="input-field" required>
      <br>
      <button type="submit" style="padding: 10px; margin-top: 20px; display: block;">Login</button>
    </form>

    <p style="margin-top: 20px;">Don't have an account? <a href="{% url 'users:user_signup' %}">Sign Up</a></p>
  </div>

  <script>
    // Redirect to the home page when clicking the "Locailable" link
    document.querySelector('a[href="{% url 'users:home' %}"]').addEventListener('click', function(event) {
      event.preventDefault();
      window.location.href = '{% url 'users:home' %}';  // Update the URL here
    });
  </script>
{% endblock %}

users/templates/users/user_profile.html
<!-- users/templates/users/user_profile.html -->

{% extends 'base.html' %}

{% block content %}
  <h2>User Profile</h2>
  <!-- Display user profile information and reviews here -->
{% endblock %}

users/templates/users/user_signup.html
<!-- users/templates/users/register.html -->
{% extends 'base.html' %}

{% block title %}Register{% endblock %}

{% block content %}
  <div style="text-align: center; margin-top: 50px;">
    <h1>{{ page|title }}</h1>

    <!-- Registration Form -->
    <form method="POST" action="{% url 'users:user_signup' %}" id="registerForm" style="text-align: left; padding: 20px; border: 1px solid #ccc; border-radius: 8px;">
      {% csrf_token %}

      <label for="{{ form.username.id_for_label }}">Username:</label>
      <br>
      <input type="text" name="{{ form.username.name }}" id="{{ form.username.id_for_label }}" required>
      <br><br>

      <label for="{{ form.first_name.id_for_label }}">First Name:</label>
      <br>
      <input type="text" name="{{ form.first_name.name }}" id="{{ form.first_name.id_for_label }}" required>
      <br><br>

      <label for="{{ form.last_name.id_for_label }}">Last Name:</label>
      <br>
      <input type="text" name="{{ form.last_name.name }}" id="{{ form.last_name.id_for_label }}" required>
      <br><br>

      <label for="{{ form.email.id_for_label }}">Email:</label>
      <br>
      <input type="email" name="{{ form.email.name }}" id="{{ form.email.id_for_label }}" required>
      <br><br>

      <label for="{{ form.password1.id_for_label }}">Password:</label>
      <br>
      <input type="password" name="{{ form.password1.name }}" id="{{ form.password1.id_for_label }}" pattern="(?=.*\d)(?=.*[a-z])(?=.*[A-Z]).{8,}" title="Must contain at least one number, one lowercase letter, one uppercase letter, and at least 8 characters" required>
      <br><br>

      <label for="{{ form.password2.id_for_label }}">Confirm Password:</label>
      <br>
      <input type="password" name="{{ form.password2.name }}" id="{{ form.password2.id_for_label }}" required>
      <br><br>

      <p style="font-weight: bold;">Password must contain at least one number, one lowercase letter, one uppercase letter, and at least 8 characters.</p>

      <button type="submit" style="padding: 10px; margin-top: 10px; display: block; font-weight: bold;">Sign Up</button>
    </form>
  </div>
{% endblock %}